### ISSUE TITLE
AVR schematic

### ISSUE THREAD

**Issue by SiChiTong** [jackw01/testbot86#1]
Dear Sir
   Thanks for sharing your awesome design!
   Would you mind sharing the AVR connections in EDA/fritizing?

Many thanks and regards
Don

**Comment by jackw01** [comment]
The prototype board in my robot can be replaced with just about any ATmega328 board that fits in that space. I just built it this way because at the time, I had a few DIP28-package ATmega328 chips on hand and no small development boards. The connections are listed in `constants.hpp` in the firmware repo:

```
const uint8_t PinMotorLPWM = 6;
const uint8_t PinMotorLDir = 7;
const uint8_t PinMotorRPWM = 11;
const uint8_t PinMotorRDir = 10;
const uint8_t PinLeftEncoderA = 2;
const uint8_t PinLeftEncoderB = 4;
const uint8_t PinRightEncoderA = 3;
const uint8_t PinRightEncoderB = 5;
const uint8_t PinLEDs = 13;
const uint8_t PinBatteryVoltageDivider = 3;
```

The gyro is connected through I2C and the Raspberry Pi serial port is connected to the AVR's serial port through a level shifter. The battery voltage is sent to analog input 3 through a 2:1 voltage divider. All the control electronics are powered through a step up/step down voltage regulator (https://www.pololu.com/product/2119) that will keep the AVR and Raspberry Pi running even if the battery voltage drops below 5V.

**Comment by SiChiTong** [comment]
I see
Many thanks for your kind response, sir
